Gingene/Concert-now

package-lock.json
package.json
src/components/ui/avatar/Avatar.vue
src/components/ui/avatar/AvatarFallback.vue
src/components/ui/avatar/AvatarImage.vue
src/components/ui/avatar/index.js
src/components/ui/badge/Badge.vue
src/components/ui/badge/index.js
src/components/ui/form/FormControl.vue
src/components/ui/form/FormDescription.vue
src/components/ui/form/FormItem.vue
src/components/ui/form/FormLabel.vue
src/components/ui/form/FormMessage.vue
src/components/ui/form/index.js
src/components/ui/form/useFormField.js
src/components/ui/popover/Popover.vue
src/components/ui/popover/PopoverContent.vue
src/components/ui/popover/PopoverTrigger.vue
src/components/ui/popover/index.js
src/components/ui/tooltip/Tooltip.vue
src/components/ui/tooltip/TooltipContent.vue
src/components/ui/tooltip/TooltipProvider.vue
src/components/ui/tooltip/TooltipTrigger.vue
src/components/ui/tooltip/index.js

1.新增UI: Avatar, Badge, Popover, Tooltip
2.新增: vee-validate/rules, vee-validate/i18n

chore: 🤖 新增一些UI和vee-validate相關套件

---

src/assets/main.scss
src/assets/scss/_components.scss
src/components/layout/FooterCopyRight.vue
src/components/layout/FooterNav.vue
src/components/layout/HeaderNav.vue
src/router/index.js
src/views/NotFound.vue
src/views/front/FrontView.vue
src/views/front/HomeView.vue
tailwind.config.js

1. 新增footerNav
2. 新增footer
3. 更新修改部分導覽列
4. 修改預設大標題字距調整為預設

feat: 🎸 新增footer-nav和footer和更新部分上方導覽列

---

src/assets/main.scss

Google icons 全部樣式都擴增進來了～也測試過全部可以正常使用

chore: 🤖 google icons extension - material symbols & icons

---

src/App.vue
src/components/FormTest.vue
src/components/ui/toast/Toast.vue
src/components/ui/toast/ToastAction.vue
src/components/ui/toast/ToastClose.vue
src/components/ui/toast/ToastDescription.vue
src/components/ui/toast/ToastProvider.vue
src/components/ui/toast/ToastTitle.vue
src/components/ui/toast/ToastViewport.vue
src/components/ui/toast/Toaster.vue
src/components/ui/toast/index.js
src/components/ui/toast/use-toast.js
src/views/front/BaseView.vue

1. 新增toast-UI
2. 新增FormTest.vue做為參考

feat: 🎸 新增toast-UI並新增FormTest元件做為參考

---

src/components/layout/FooterNav.vue
src/components/layout/HeaderNav.vue
src/router/index.js
src/stores/venues.js
src/views/front/VenueSingleView.vue
src/views/front/VenuesView.vue

1. 新增場地頁面
2. 新增單一場地頁面
3. 新增header導覽列效果
4. 新增footer導覽列轉場效果

feat: 🎸 新增前台場地和單一場地頁面,新增導覽頁效果

---

src/api/index.js
src/views/front/LoginView.vue

異動：'Content-Type': 'multipart/form-data' 和登入頁。Celine 自己 merge~ 穴穴！

feat: 🎸 前台登入頁完成(表單驗證下次新增)

---

src/assets/scss/_components.scss
src/assets/scss/_utilities.scss
src/components/custom/TitleComponent.vue
src/main.js
src/router/index.js
src/views/front/AboutUsView.vue

麻煩審閱惹，甘蝦🦐
- 在 _utilities.scss 新增 bg-shadow-trans-text class：毛玻璃效果(透明) 背景
- 標題元件：改用h2標籤，字體大小改成與h1標籤相同的 text-5xl
- _utilities.scss /  box-shadow-light2：blur 數值 25→12，降低模糊(才能看出字)

關於我們頁面切版完畢

---

src/views/admin/AnalysisView.vue

flex 換成 grid 好像有穩定一點點，但視窗縮放造成的畫面跑版主要問題出在 C3.js 的圖表～
除非換圖表套件不然暫時無解

後台分析頁更換排版成 grid

---

src/router/index.js

feat: 🎸 新增進入後台所需權限

---

src/router/index.js
src/views/admin/AdminConcertsView.vue

1. 修復直接使用連結無法進入後台
2. concert命名修正

fix: 🐛 修復直接使用連結無法進入後台

---

src/router/index.js
src/views/front/LoginView.vue
src/views/front/Members.vue

異動部分：router 新增路徑(member)、login 頁面取消tab跳轉、新增前台會員個人頁面(Members.vue)

feat: 🎸 前台會員個人頁面切版完成

---

src/hooks/useTimeCountryFilter.js
src/stores/concerts.js
src/views/front/ConcertSingleView.vue
src/views/front/ConcertsView.vue

新增按鈕篩選功能
可於前台表演者篩選、前後台演唱會篩選時使用，兩個篩選條件(時間與國籍)綁在一起
使用程式碼請參考  ConcertView.vue & store/concert.js
函式寫在 hooks/useTimeCountryFilter.js
使用說明：
```html
// ConcertView.vue
// 時間篩選按鈕區塊
<div class="space-y-4 space-x-4 space-x-reverse -m-1 p-1">
<Button variant="tiffany-outline" size="base" class="me-4" **@click="getConcerts('/*時間篩選為'time'、國籍篩選為'country'*/,'all')"**> 全部 </Button>
<template v-for="time in timeRanges" :key="time">
<Button variant="tiffany-outline" size="base" **@click="getConcerts('/*時間篩選為'time'、國籍篩選為'country'*/',time)"**> {{ time }} </Button>
</template>
</div>
<script>
import { useConcertsStore } from '@/stores/concerts'; // 函式是在 store 匯入，所以這邊只需要匯入 store
export default {
data() {
return {
// 設定按鈕選項
timeRanges: ['本日', '本週', '本月'],
countryRanges: ['台灣', '日本', '韓國', '歐美', '其他'],
};
}, …
```

feat: 🎸 按鈕篩選功能(時間與國籍)

---

src/stores/concerts.js
src/views/front/ConcertSingleView.vue

feat: 🎸 單一演唱會畫面渲染調整

---

src/views/admin/AnalysisView.vue

刪除演唱會檢索的換頁區塊，暫時不做
演唱會資料改從 concerts store 取

feat: 🎸 修復後台分析報表-演唱會檢索區塊

---

src/assets/main.scss
src/hooks/useDarkAlert.js
src/stores/concerts.js
src/stores/user.js
src/views/front/ConcertSingleView.vue
src/views/front/ConcertsView.vue
tailwind.config.js

- 篩選按鈕的樣式改用 v-bind 切換
- 單一頁面跟總覽頁面皆可使用收藏功能
- 新增一個深灰色 black-90
- 新增的深色版 Alert 被打包成 hook 了👜🏃‍♀️
使用時機：未登入但執行收藏動作時
使用說明：
```html
import useDarkAlert from '@/hooks/useDarkAlert';
const { swalWithStylingButtons } = useDarkAlert();
swalWithStylingButtons.fire({
title: '/*標題文字*/',
showCancelButton: true,
confirmButtonText: '/*確認按鈕文字*/',
showConfirmButton: /*如果不需要確認按鈕就用false，需要的話把這行刪掉*/,
buttonsStyling: false,/*這行是把預設的樣式關掉，不用動它*/
})
.then((result) => {
if (result.isConfirmed) { 
/*'確認按鈕'被點擊後執行的動作*/
}
});
```

篩選按鈕樣式切換、演唱會收藏功能、深色 alert

---

src/views/front/HomeView.vue
tailwind.config.js

首頁場地部分完成切版+RWD+Swiper輪播；tailwind.config.js 新增斷點：xs: '480px'

test: 💍 首頁場地評論切版+RWD+Swiper輪播

---

src/components/layout/HeaderNav.vue
src/router/index.js
src/views/front/VenuesView.vue

1. 新增header搜尋功能
2. 修正無token時進入後台，通知使用者重新登入
3.

feat: 🎸 新增header搜尋功能

---

src/api/index.js
src/assets/scss/_components.scss
src/router/index.js
src/views/front/ArtistSingleView.vue
src/views/front/ArtistsView.vue

**更新項目**
1. 新增單一表演者 API
2. 新增input 篩選功能(表演者總覽頁面)
3. 刪除多餘的程式碼

feat: 🎸 新增單一表演者API及input篩選功能(表演者總覽)

---

src/components/layout/HeaderNav.vue
src/stores/venues.js
src/views/front/VenueSingleView.vue
src/views/front/VenuesView.vue

feat: 🎸 新增評論完成

---

src/api/index.js
src/views/front/ArtistsView.vue
src/views/front/HomeView.vue

首頁header RWD完成，等pull新版下來才可以綁定search開啟modal。

feat: 🎸 首頁header RWD完成

---

src/components/admin/AdminPlaylists/SongList.vue
src/components/layout/HeaderNav.vue
src/stores/songs.js
src/views/admin/AdminCommentsView.vue
src/views/admin/AdminPlaylistsView.vue
src/views/front/VenueSingleView.vue

feat: 🎸 修復後台歌單綁定頁數

---

src/stores/venues.js
src/views/front/HomeView.vue

首頁Venue完成，剩Swipe功能有小bug，和search要開modal

feat: 🎸 首頁Venue完成

---

src/api/index.js
src/stores/artists.js
src/views/front/ArtistSingleView.vue
src/views/front/ArtistsView.vue
src/views/front/ConcertsView.vue
src/views/front/Members.vue

使用者頁面完成，有幾個待修改的地方：
1. user 頭貼沒有完全去背，要換照片
2. 警告次數在 pinia 裡沒有存放到
3. 表演者區塊在 xl:1280px 高度有問題

feat: 🎸 使用者個人頁面完成

---

src/api/index.js
src/components/layout/HeaderNav.vue
src/views/front/ArtistSingleView.vue
src/views/front/ArtistsView.vue

**更新內容**
1. 新增表演者總覽頁面-篩選功能
2. 修改一些樣式距離(padding or margin)

feat: 🎸 新增表演者頁面-篩選按鈕

---

src/api/index.js
src/assets/scss/_utilities.scss
src/router/index.js
src/stores/venues.js
src/views/NotFound.vue
src/views/front/VenueSingleView.vue

1. 修改400錯誤路由處理
2. 訊息由sweetAlert統一成toast
3. 修改單一場地選擇陰影

feat: 🎸 修改400錯誤路由處理，修改單一場地選擇陰影

---

src/assets/scss/_utilities.scss
src/views/front/LoginView.vue

登入頁樣式調整
- 非active的按鈕背景色為black-85
- 確認送出按鈕 variant="white-outline" ，hover 時會變螢光白
- input 間距小小調大

feat: 🎸 修改樣式

---

.eslintrc.cjs
src/views/admin/AdminPlaylistsView.vue
src/views/front/ArtistSingleView.vue
src/views/front/ArtistsView.vue
src/views/front/VenueSingleView.vue

**eslint會針對console.log提出警告，使用npm run lint之後請清除自己寫的console.log**
一般更新
1. 更改歌單管理新開連結
2. 新增單一場地可點擊、樣式改成hover
3. 單一場地評論排版修正避免圖片變形

feat: 🎸 單一場地圖片功能修復

---

src/api/index.js
src/components/FormTest.vue
src/components/layout/HeaderNav.vue
src/stores/user.js
src/stores/venues.js
src/views/front/HomeView.vue
src/views/front/VenueSingleView.vue

1. 增加首頁可點擊Concert Now呼叫header modal
2. 調整單一場地頁面modal大小
3. 設定使用者頁loading

feat: 🎸 增加首頁可點擊Concert Now

---

src/components/front/login/loginComponent.vue
src/views/front/LoginView.vue
src/views/front/SingUpView.vue

fix: 🐛 alert 改為 toast

---

src/assets/scss/_utilities.scss
src/stores/concerts.js
src/views/front/ConcertSingleView.vue

1. 標題 text-stroke-title 改粗細 2px → 1px
2. 單一演唱會頁面場地區塊使用 venue store 取得評論與場地畫面

feat: 🎸 演唱會場地區塊串 API

---

src/components/front/login/loginComponent.vue
src/views/front/LoginView.vue
src/views/front/SingUpView.vue
src/views/front/VenueSingleView.vue

1. 單一場地新增評論限制上傳圖片大小
2. 修改註冊驗證最小值

feat: 🎸 新增限制檔案大小

---

src/assets/scss/_components.scss
src/views/front/ArtistSingleView.vue
src/views/front/ArtistsView.vue
src/views/front/ConcertsView.vue
src/views/front/VenuesView.vue

1. 單一表演者未登入狀態追蹤，跳出登入請求 AlertDialog (移除 sweetalet、HoverCard)
2. 統一演唱會、表演者、場地樣式

feat: 🎸 表演者 alert 修改，統一樣式

---

src/assets/scss/_utilities.scss
src/components/front/login/loginComponent.vue
src/components/ui/form/FormControl.vue
src/components/ui/form/FormItem.vue
src/components/ui/form/FormLabel.vue
src/components/ui/form/FormMessage.vue
src/views/front/HomeView.vue
src/views/front/LoginView.vue
src/views/front/SingUpView.vue

fix: 🐛 登入頁調整完成

---

src/stores/concerts.js
src/views/admin/AdminMembersView.vue
src/views/front/ConcertSingleView.vue
src/views/front/ConcertsView.vue
src/views/front/VenueSingleView.vue

1. fix bug：歌曲新增後未出現
將 songList 改放 computed ，return 出經過排序好的歌單
2. 調整單一場地座位區下拉選單樣式

feat: 🎸 新增歌曲功能優化，調整單一場地樣式

---

src/stores/concerts.js
src/views/admin/AdminMembersView.vue
src/views/front/ConcertSingleView.vue
src/views/front/ConcertsView.vue

feat: 🎸 前台演唱會換頁

---

src/views/front/ArtistsView.vue
src/views/front/VenuesView.vue

1. 修正表演者分頁前後頁禁用問題
2. 修正場地分頁前後頁禁用問題

fix: 🐛 分頁前後頁禁用問題修正

---

src/views/admin/AdminSettingsView.vue

refactor: 💡 後台設定頁程式碼修改完成（樣式無異動）

---

src/components/front/login/loginComponent.vue

登入頁程式碼調整 + HoverCard 改為 Popover

refactor: 💡 登入頁程式碼調整 + HoverCard 改為 Popover

---

src/views/front/HomeView.vue

refactor: 💡 LoginComponent.vue 首字大寫

---

src/components/layout/FooterCopyRight.vue
src/views/front/ConcertSingleView.vue

單一演唱會
1. 倒計時器修改排版
2. 表演者位置修改排版
footer 
1. 修改排版與取消連結、a tag

refactor: 💡 footer 與單一演唱會倒計時器修改

---

src/views/front/HomeView.vue
tailwind.config.js

feat: 🎸 首頁artist 動畫效果修正

---

src/views/front/HomeView.vue
tailwind.config.js

refactor: 💡 微調首頁 artist 圖片位置

---

src/views/front/ConcertSingleView.vue

演唱會倒計時器動畫與文字修改
- 23:10:10 -> 23時10分10秒
- 增加倒計時器動畫

feat: 🎸 add concert countdown timer

---

src/views/front/HomeView.vue

首頁 sections 加上 id 讓區域判讀更容易。微調程式碼。

refactor: 💡 首頁 sections 加上 id 讓區域判讀更容易。微調程式碼。

---

src/views/front/HomeView.vue

refactor: 💡 首頁 sections 加上 id 容易區分

---

src/assets/scss/_components.scss
src/components/ui/dialog/DialogScrollContent.vue
src/stores/venues.js
src/views/admin/AdminVenuesView.vue

feat: 🎸 後台場地頁 新增、刪除單一、刪除多筆功能

---

src/views/front/FrontView.vue

feat: 🎸 手機/平板寬度時不顯示滑鼠動畫

---

src/stores/venues.js

fix: 🐛 修改場地不可刪的內容

---

src/components/front/LoginComponent.vue
src/components/layout/AdminNav.vue
src/stores/user.js

refactor: 💡 重構header程式碼

---

src/api/admin/all.js
src/stores/user.js
src/views/admin/AdminMembersView.vue

後台會員管理頁 Pagination 完成

---

README.md

feat: 🎸 新增readme流程演示

---

src/views/admin/AdminConcertsView.vue
src/views/admin/AdminSettingsView.vue
src/views/admin/AdminVenuesView.vue

feat: 🎸 後台 演唱會、場地、設定頁RWD

---

src/components/layout/AdminSideBar.vue
src/views/front/ArtistsView.vue

**新增內容:** 
1. 追蹤功能微調
2. 後台 sidebar 樣式調整

追蹤功能微調 & 樣式調整

---

src/views/front/HomeView.vue

首頁 Artists carousel 改為 <details> 建構

refactor: 💡 Artists carousel 改為 <details> 建構

---

src/views/front/HomeView.vue

Reverts Gingene/Concert-now#187

Revert "style: 💄 prettier 更新 format"
